--- #YAML:1.0
name:                Net-UPCDatabase
version:             0.07
abstract:            ~
license:             ~
author:              
    - Dusty Wilson <cpan-Net-UPCDatabase@dusty.hey.nu>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Frontier::Client:              0
    Frontier::RPC2:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
